services:
  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    image: test-app
    container_name: test-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www